version: 3.2.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: FluentBootstrap.sln

after_test:
  - ps: .\nuget-pack.ps1

artifacts:
  - path: FluentBootstrap\bin\Release\FluentBootstrap.dll
    name: FluentBootstrap.dll
  - path: '**\FluentBootstrap.*.nupkg'
  
